### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by wthrees** [wuchuanpeng/no-vue3-cron#1]
具体秒数选择框，选择下拉框时，只要点击，时间表达式弹框就会隐藏，下拉框会直接定位到页面最右边。这怎么处理？

**Comment by inonone** [comment]
[demo](https://nonone.cc/no-vue3-cron/)中没有发现这个问题，方便截图吗

**Comment by LuThreeGold** [comment]
我也遇到了相同的问题。
`<el-popover v-model:visible="state.cronPopover" width="700px" trigger="manual">`
把v-mode去掉就没问题了

**Comment by Asia-king** [comment]
@LuThreeGold把v-model去掉，就直接调不出来了

**Comment by Asia-king** [comment]
@wuchuanpeng  
![Uploading [1698825679962.jpg…]()]   下拉框的选项就跑到左上角了，打开的窗口就关闭了

**Comment by LuThreeGold** [comment]
@Asia-king `<el-popover :visible="state.cronPopover" width="700px" trigger="manual"> ` 我是这样写的，可以正常调用

**Comment by Asia-king** [comment]
@LuThreeGold 好的，我试一下，谢谢了
